name: Auto Release

on: 
  push:
    paths:
      - build_output/firmware/*
    branches: master
  #push:
  #  tags:
  #  - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        #artifacts: "example.bin,foo/*.txt"
        artifacts: "build_output/firmware/*"
        bodyFile: "RELEASE.md"
