name: Push to Tasmota Build
on:
  push:
    paths:
      - build_output/firmware/*
    branches: master

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'build_output/firmware/'
        destination_repo: 'racksync/tasmota-build'
        destination_folder: '/'
        user_email: 'info@racksync.com'
        user_name: 'racksync'
        commit_message: 'Tasmota build has been updated'